version: '3'

networks:
  app-connect:
    driver: bridge

services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: 'test-nestjs-graphql-prisma'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
    ports:
      - '5555:5432'
    networks:
      - app-connect

  api:
    depends_on:
      - database
    build:
      dockerfile: 'Dockerfile'
      context: .
    environment:
      DATABASE_URL: 'postgresql://postgres:postgres@database/test-nestjs-graphql-prisma'
      PORT: 3000
    volumes:
      - './:/usr/app'
    ports:
      - '3000:3000'
    networks:
      - app-connect
